import React from 'react'
import { TinyMceDoc } from '../Components/index.js'
import { useParams } from 'react-router-dom';

function TemplateDoc() {
  const { id } = useParams();
  const allcontent = [{ id: 1,name:"Resume" , content: "<p>Your Name<br /> 123 Your Street<br /> Your City, ST 12345<br /> (123) 456-7890<br /> no_reply@example.com</p><p>4th September 20XX</p><p>Ronny Reader<br />CEO, Company Name<br />123 Address St<br />Anytown, ST 12345</p><p>Dear Ms. Reader,</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p><p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p><p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.</p><p>Sincerely,</p><p><br /><br />Your Name</p>"},
    {id:2,name:"Resume" ,content: '<h1>Your Name</h1><p><em>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</em><br />123 Your Street | Your City, ST 12345<br />(123) 456-7890 | no_reply@example.com</p><hr /><h2>EXPERIENCE</h2><p><strong>Company, Location — Job Title</strong><br /><em>MONTH 20XX - PRESENT</em><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.</p><p><strong>Company, Location — Job Title</strong><br /><em>MONTH 20XX - MONTH 20XX</em><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.</p><p><strong>Company, Location — Job Title</strong><br /><em>MONTH 20XX - MONTH 20XX</em><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.</p><h2>EDUCATION</h2><p><strong>School Name, Location — Degree</strong><br /><em>MONTH 20XX - MONTH 20XX</em><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.</p><p><strong>School Name, Location — Degree</strong><br /><em>MONTH 20XX - MONTH 20XX</em><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam.</p><h2>PROJECTS</h2><p><strong>Project Name — Detail</strong><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p><h2>SKILLS</h2><ul><li>Lorem ipsum dolor sit amet.</li><li>Consectetuer adipiscing elit.</li><li>Sed diam nonummy nibh euismod tincidunt.</li><li>Laoreet dolore magna aliquam erat volutpat.</li></ul><h2>AWARDS</h2><p><strong>Lorem ipsum dolor sit amet</strong><br />Consectetuer adipiscing elit, Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p><p><strong>Lorem ipsum dolor sit amet</strong><br />Consectetuer adipiscing elit, Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p><h2>LANGUAGES</h2><p>Lorem ipsum, Dolor sit amet, Consectetuer</p>'},
    {id:3,name:"Resume" ,content: '<h1>Hello</h1><h2>I’m Your Name</h2><p>123 YOUR STREET<br />YOUR CITY, ST 12345<br />(123) 456-7890<br />NO_REPLY@EXAMPLE.COM</p><h3>Skills</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac interdum nisi. Sed in consequat mi. Sed pulvinar lacinia felis eu finibus.</p><h3>Experience</h3><p><strong>MONTH 20XX - PRESENT</strong><br />Company Name, Location - Job Title</p><ul><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li>Aenean ac interdum nisi. Sed in consequat mi.</li><li>Sed in consequat mi, sed pulvinar lacinia felis eu finibus.</li></ul><p><strong>MONTH 20XX - MONTH 20XX</strong><br />Company Name, Location - Job Title</p><ul><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li>Aenean ac interdum nisi. Sed in consequat mi.</li></ul><p><strong>MONTH 20XX - MONTH 20XX</strong><br />Company Name, Location - Job Title</p><ul><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li>Aenean ac interdum nisi. Sed in consequat mi.</li><li>Sed pulvinar lacinia felis eu finibus.</li></ul><h3>Education</h3><p><strong>MONTH 20XX - MONTH 20XX</strong><br />College Name, Location - Degree</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.</p><h3>Awards</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br />Aenean ac interdum nisi.</p>'},
    {id:4,name:"Resume" ,content: '<h1>Project Name</h1><p>09.04.20XX</p><p>─</p><p><strong>Your Name</strong><br />Your Company<br />123 Your Street<br />Your City, ST 12345</p><h2>Overview</h2><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper.</p><h2>Goals</h2><ul><li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</li><li>Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</li></ul><h2>Specifications</h2><p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.</p><h3>Lorem Ipsum</h3><p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p><h2>Milestones</h2><p><strong>Lorem ipsum</strong><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p><p><strong>Dolor sit amet</strong><br />Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>'},
    {id:5,name:"Resume" ,content: '<p><strong>Your Company</strong><br />123 Your Street<br />Your City, ST 12345<br />(123) 456 - 7890</p><h1>Product Brochure</h1><p>September 04, 20XX</p><h2>Product Overview</h2><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p><h3>Lorem ipsum</h3><p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem.</p><h3>Lorem ipsum</h3><p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p><h3>Dolor sit</h3><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p><h2>Details</h2><p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p>'},
    {id:6,name:"Resume" ,content: '<p style="text-align: center;"><strong>COURSE NAME</strong><br /><strong>REPORT TITLE</strong><br />LOREM IPSUM DOLOR SIT AMET</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p><h3>Lorem ipsum</h3><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.</p><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p><h3>Dolor sit amet</h3><p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan.</p>'},
  ]
  return (
    <div>
      {allcontent.map((item) => (
        <div key={item.id}>
          {id == item.id &&
          <div>
            <h1 className='text-center text-[28px] mt-4'>{item.name} Template</h1>
            <div className='w-350 ml-20 mt-5'>
              <TinyMceDoc valueonly={item.content} />
            </div>
          </div> 
          }
        </div>
      ))}
    </div>
  )
}

export default TemplateDoc
